[project]
name = "boat-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "lab>=8.4",
    "numpy>=2.3.2",
    "pygame-ce>=2.5.5",
]
